// Code generated by "genprotocol -ver=ed65a653bd268dc21902d5d07939f7bfc1ba6b98026a426c30526d9f59ba8d12 -basedir=. -prefix=w2d -statstype=int"

package w2d_handlereq

/* bytes base fn map api template , unmarshal in api
	var DemuxReq2BytesAPIFnMap = [...]func(
		me interface{}, hd w2d_packet.Header, rbody []byte) (
		w2d_packet.Header, interface{}, error){
	w2d_idcmd.Invalid: bytesAPIFn_ReqInvalid,
w2d_idcmd.EnterStage: bytesAPIFn_ReqEnterStage,
w2d_idcmd.ChatToStage: bytesAPIFn_ReqChatToStage,
w2d_idcmd.Heartbeat: bytesAPIFn_ReqHeartbeat,

}   // DemuxReq2BytesAPIFnMap

	func bytesAPIFn_ReqInvalid(
		me interface{}, hd w2d_packet.Header, rbody []byte) (
		w2d_packet.Header, interface{}, error) {
		// robj, err := w2d_json.UnmarshalPacket(hd, rbody)
		// if err != nil {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", rbody)
		// }
		// recvBody, ok := robj.(*w2d_obj.ReqInvalid_data)
		// if !ok {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		// }
		// _ = recvBody

		sendHeader := w2d_packet.Header{
			ErrorCode : w2d_error.None,
		}
		sendBody := &w2d_obj.RspInvalid_data{
		}
		return sendHeader, sendBody, nil
	}

	func bytesAPIFn_ReqEnterStage(
		me interface{}, hd w2d_packet.Header, rbody []byte) (
		w2d_packet.Header, interface{}, error) {
		// robj, err := w2d_json.UnmarshalPacket(hd, rbody)
		// if err != nil {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", rbody)
		// }
		// recvBody, ok := robj.(*w2d_obj.ReqEnterStage_data)
		// if !ok {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		// }
		// _ = recvBody

		sendHeader := w2d_packet.Header{
			ErrorCode : w2d_error.None,
		}
		sendBody := &w2d_obj.RspEnterStage_data{
		}
		return sendHeader, sendBody, nil
	}

	func bytesAPIFn_ReqChatToStage(
		me interface{}, hd w2d_packet.Header, rbody []byte) (
		w2d_packet.Header, interface{}, error) {
		// robj, err := w2d_json.UnmarshalPacket(hd, rbody)
		// if err != nil {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", rbody)
		// }
		// recvBody, ok := robj.(*w2d_obj.ReqChatToStage_data)
		// if !ok {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		// }
		// _ = recvBody

		sendHeader := w2d_packet.Header{
			ErrorCode : w2d_error.None,
		}
		sendBody := &w2d_obj.RspChatToStage_data{
		}
		return sendHeader, sendBody, nil
	}

	func bytesAPIFn_ReqHeartbeat(
		me interface{}, hd w2d_packet.Header, rbody []byte) (
		w2d_packet.Header, interface{}, error) {
		// robj, err := w2d_json.UnmarshalPacket(hd, rbody)
		// if err != nil {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", rbody)
		// }
		// recvBody, ok := robj.(*w2d_obj.ReqHeartbeat_data)
		// if !ok {
		// 	return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		// }
		// _ = recvBody

		sendHeader := w2d_packet.Header{
			ErrorCode : w2d_error.None,
		}
		sendBody := &w2d_obj.RspHeartbeat_data{
		}
		return sendHeader, sendBody, nil
	}

*/
