// Code generated by "genprotocol -ver=311c9c290570c203090ea3d20ebbf006c810eb958a7a96aef942015fbfd89d2f -basedir=. -prefix=w2d -statstype=int"

package w2d_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid        NotiID = iota //
	StageInfo                    // // game stage info to display
	StatsInfo                    // // game stats info
	StageBroadCast               //

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count]string{
	Invalid:        "Invalid",
	StageInfo:      "StageInfo",
	StatsInfo:      "StatsInfo",
	StageBroadCast: "StageBroadCast",
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}

var _string2NotiID = map[string]NotiID{
	"Invalid":        Invalid,
	"StageInfo":      StageInfo,
	"StatsInfo":      StatsInfo,
	"StageBroadCast": StageBroadCast,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
