// Code generated by "genprotocol -ver=8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a -basedir=. -prefix=w2d -statstype=int"

package w2d_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid        NotiID = iota //
	StageInfo                    // // game stage info to display
	StatsInfo                    // // game stats info
	StageBroadCast               //

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count]string{
	Invalid:        "Invalid",
	StageInfo:      "StageInfo",
	StatsInfo:      "StatsInfo",
	StageBroadCast: "StageBroadCast",
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}

var _string2NotiID = map[string]NotiID{
	"Invalid":        Invalid,
	"StageInfo":      StageInfo,
	"StatsInfo":      StatsInfo,
	"StageBroadCast": StageBroadCast,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
