// Code generated by "genprotocol -ver=0088cae732cbbc92d93b745e6f587bb9319940346f41b718b0293a0b56942cc3 -basedir=. -prefix=w2d -statstype=int"

package w2d_version

const ProtocolVersion = "0088cae732cbbc92d93b745e6f587bb9319940346f41b718b0293a0b56942cc3"
