// Code generated by "genprotocol -ver=8ce3a4010a59de778695c59389c0fd9a3938197ee346a449f005b536d94d0e60 -basedir=protocol_w2d -prefix=w2d -statstype=int"

package w2d_version

const ProtocolVersion = "8ce3a4010a59de778695c59389c0fd9a3938197ee346a449f005b536d94d0e60"
