// Code generated by "genprotocol -ver=8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a -basedir=. -prefix=w2d -statstype=int"

package w2d_version

const ProtocolVersion = "8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a"
