// Code generated by "genprotocol -ver=eb884c961074aeaf0b613a0d0567567c029f9b9d5b9a686f9b1b7ade5f686087 -basedir=. -prefix=w2d -statstype=int"

package w2d_idcmd

import "fmt"

type CommandID uint16 // use in packet header, DO NOT CHANGE
const (
	Invalid    CommandID = iota //
	Login                       //
	Heartbeat                   //
	Chat                        //
	EnterStage                  //

	CommandID_Count int = iota
)

var _CommandID2string = [CommandID_Count][2]string{
	Invalid:    {"Invalid", ""},
	Login:      {"Login", ""},
	Heartbeat:  {"Heartbeat", ""},
	Chat:       {"Chat", ""},
	EnterStage: {"EnterStage", ""},
}

func (e CommandID) String() string {
	if e >= 0 && e < CommandID(CommandID_Count) {
		return _CommandID2string[e][0]
	}
	return fmt.Sprintf("CommandID%d", uint16(e))
}

func (e CommandID) CommentString() string {
	if e >= 0 && e < CommandID(CommandID_Count) {
		return _CommandID2string[e][1]
	}
	return ""
}

var _string2CommandID = map[string]CommandID{
	"Invalid":    Invalid,
	"Login":      Login,
	"Heartbeat":  Heartbeat,
	"Chat":       Chat,
	"EnterStage": EnterStage,
}

func String2CommandID(s string) (CommandID, bool) {
	v, b := _string2CommandID[s]
	return v, b
}
