// Code generated by "genprotocol -ver=8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a -basedir=. -prefix=w2d -statstype=int"

package w2d_error

import "fmt"

type ErrorCode uint16 // use in packet header, DO NOT CHANGE
const (
	None             ErrorCode = iota //
	ActionProhibited                  //
	ObjectNotFound                    //
	ActionChaned                      //
	ActionCanceled                    //

	ErrorCode_Count int = iota
)

var _ErrorCode2string = [ErrorCode_Count]string{
	None:             "None",
	ActionProhibited: "ActionProhibited",
	ObjectNotFound:   "ObjectNotFound",
	ActionChaned:     "ActionChaned",
	ActionCanceled:   "ActionCanceled",
}

func (e ErrorCode) String() string {
	if e >= 0 && e < ErrorCode(ErrorCode_Count) {
		return _ErrorCode2string[e]
	}
	return fmt.Sprintf("ErrorCode%d", uint16(e))
}

// implement error interface
func (e ErrorCode) Error() string {
	return "w2d_error." + e.String()
}

var _string2ErrorCode = map[string]ErrorCode{
	"None":             None,
	"ActionProhibited": ActionProhibited,
	"ObjectNotFound":   ObjectNotFound,
	"ActionChaned":     ActionChaned,
	"ActionCanceled":   ActionCanceled,
}

func String2ErrorCode(s string) (ErrorCode, bool) {
	v, b := _string2ErrorCode[s]
	return v, b
}
