// Code generated by "genprotocol -ver=8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a -basedir=. -prefix=w2d -statstype=int"

package w2d_const

/*  copy to no _gen file, and edit it
const (
	// MaxBodyLen set to max body len, affect send/recv buffer size
	MaxBodyLen = 0xfffff
	// PacketBufferPoolSize max size of pool packet buffer
	PacketBufferPoolSize = 100

	// ServerAPICallTimeOutDur api call watchdog timer
	ServerAPICallTimeOutDur = time.Second * 2
)
*/
