// Code generated by "genenum.exe -typename=TeamType -packagename=teamtype -basedir=enum -vectortype=int"

package teamtype_vector

import (
	"bytes"
	"fmt"
	"html/template"
	"net/http"

	"github.com/kasworld/gowasm2dgame/enum/teamtype"
)

type TeamTypeVector [teamtype.TeamType_Count]int

func (es TeamTypeVector) String() string {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "TeamTypeVector[")
	for i, v := range es {
		fmt.Fprintf(&buf,
			"%v:%v ",
			teamtype.TeamType(i), v)
	}
	buf.WriteString("]")
	return buf.String()
}
func (es *TeamTypeVector) Dec(e teamtype.TeamType) {
	es[e] -= 1
}
func (es *TeamTypeVector) Inc(e teamtype.TeamType) {
	es[e] += 1
}
func (es *TeamTypeVector) Add(e teamtype.TeamType, v int) {
	es[e] += v
}
func (es *TeamTypeVector) SetIfGt(e teamtype.TeamType, v int) {
	if es[e] < v {
		es[e] = v
	}
}
func (es TeamTypeVector) Get(e teamtype.TeamType) int {
	return es[e]
}

// Iter return true if iter stop, return false if iter all
// fn return true to stop iter
func (es TeamTypeVector) Iter(fn func(i teamtype.TeamType, v int) bool) bool {
	for i, v := range es {
		if fn(teamtype.TeamType(i), v) {
			return true
		}
	}
	return false
}

// VectorAdd add element to element
func (es TeamTypeVector) VectorAdd(arg TeamTypeVector) TeamTypeVector {
	var rtn TeamTypeVector
	for i, v := range es {
		rtn[i] = v + arg[i]
	}
	return rtn
}

// VectorSub sub element to element
func (es TeamTypeVector) VectorSub(arg TeamTypeVector) TeamTypeVector {
	var rtn TeamTypeVector
	for i, v := range es {
		rtn[i] = v - arg[i]
	}
	return rtn
}

func (es *TeamTypeVector) ToWeb(w http.ResponseWriter, r *http.Request) error {
	tplIndex, err := template.New("index").Funcs(IndexFn).Parse(`
		<html>
		<head>
		<title>TeamType statistics</title>
		</head>
		<body>
		<table border=1 style="border-collapse:collapse;">` +
		HTML_tableheader +
		`{{range $i, $v := .}}` +
		HTML_row +
		`{{end}}` +
		HTML_tableheader +
		`</table>
	
		<br/>
		</body>
		</html>
		`)
	if err != nil {
		return err
	}
	if err := tplIndex.Execute(w, es); err != nil {
		return err
	}
	return nil
}

func Index(i int) string {
	return teamtype.TeamType(i).String()
}

var IndexFn = template.FuncMap{
	"TeamTypeIndex": Index,
}

const (
	HTML_tableheader = `<tr>
		<th>Name</th>
		<th>Value</th>
		</tr>`
	HTML_row = `<tr>
		<td>{{TeamTypeIndex $i}}</td>
		<td>{{$v}}</td>
		</tr>
		`
)
