// Code generated by "genprotocol -ver=57a09ecbad7f5ac0fdfbe2818275cc4441fb7e4e19b0fd6fc4a9b1d8f9076b48 -basedir=. -prefix=w2d -statstype=int"

package w2d_obj

import "github.com/kasworld/gowasm2dgame/enums/acttype"

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqMakeTeam_data struct {
	TeamName string
}
type RspMakeTeam_data struct {
	TeamName string
	TeamID   int
}

type ReqAct_data struct {
	TeamID string
	Acts   []Act
}
type RspAct_data struct {
	Dummy uint8
}

type Act struct {
	Act      acttype.ActType
	DstPos   [2]int
	DstObjID string
	// some more?
}

type ReqState_data struct {
	Dummy uint8
}
type RspState_data struct {
	FrameInfo  interface{}
	Players    []*Player
	EffectObjs []*EffectObj
}

type Player struct {
}

type EffectObj struct {
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}
