// Code generated by "genprotocol -ver=57a09ecbad7f5ac0fdfbe2818275cc4441fb7e4e19b0fd6fc4a9b1d8f9076b48 -basedir=. -prefix=w2d -statstype=int"

package w2d_obj

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqMakeTeam_data struct {
	Dummy uint8
}
type RspMakeTeam_data struct {
	Dummy uint8
}

type ReqAct_data struct {
	Dummy uint8
}
type RspAct_data struct {
	Dummy uint8
}

type ReqState_data struct {
	Dummy uint8
}
type RspState_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}
