// Code generated by "genprotocol -ver=8ce3a4010a59de778695c59389c0fd9a3938197ee346a449f005b536d94d0e60 -basedir=protocol_w2d -prefix=w2d -statstype=int"

package w2d_obj

/* protocol template

// Invalid not used, make empty packet error
type ReqInvalid_data struct {
	Dummy uint8 // change as you need
}
// Invalid not used, make empty packet error
type RspInvalid_data struct {
	Dummy uint8 // change as you need
}

// Login make session with nickname and enter stage
type ReqLogin_data struct {
	Dummy uint8 // change as you need
}
// Login make session with nickname and enter stage
type RspLogin_data struct {
	Dummy uint8 // change as you need
}

// Heartbeat prevent connection timeout
type ReqHeartbeat_data struct {
	Dummy uint8 // change as you need
}
// Heartbeat prevent connection timeout
type RspHeartbeat_data struct {
	Dummy uint8 // change as you need
}

// Chat chat to stage
type ReqChat_data struct {
	Dummy uint8 // change as you need
}
// Chat chat to stage
type RspChat_data struct {
	Dummy uint8 // change as you need
}

// Act send user action
type ReqAct_data struct {
	Dummy uint8 // change as you need
}
// Act send user action
type RspAct_data struct {
	Dummy uint8 // change as you need
}

// Invalid
type NotiInvalid_data struct {
	Dummy uint8 // change as you need
}

// StageInfo // game stage info to display
type NotiStageInfo_data struct {
	Dummy uint8 // change as you need
}

// StatsInfo // game stats info
type NotiStatsInfo_data struct {
	Dummy uint8 // change as you need
}

// StageChat
type NotiStageChat_data struct {
	Dummy uint8 // change as you need
}

*/
