// Code generated by "genprotocol -ver=8cb09769c07a0cf3e7042afbf364a4eff2c960eafe6d9a8ccbb46041a984713a -basedir=. -prefix=w2d -statstype=int"

package w2d_obj

/* protocol template

type ReqInvalid_data struct {
	Dummy uint8
}
type RspInvalid_data struct {
	Dummy uint8
}

type ReqEnterStage_data struct {
	Dummy uint8
}
type RspEnterStage_data struct {
	Dummy uint8
}

type ReqChatToStage_data struct {
	Dummy uint8
}
type RspChatToStage_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type NotiInvalid_data struct {
	Dummy uint8
}

type NotiStageInfo_data struct {
	Dummy uint8
}

type NotiStatsInfo_data struct {
	Dummy uint8
}

type NotiStageBroadCast_data struct {
	Dummy uint8
}

*/
