// Code generated by "genprotocol -ver=0088cae732cbbc92d93b745e6f587bb9319940346f41b718b0293a0b56942cc3 -basedir=. -prefix=w2d -statstype=int"

package w2d_obj

/* protocol template

// Invalid not used, make empty packet error
type ReqInvalid_data struct {
	Dummy uint8 // change as you need
}
// Invalid not used, make empty packet error
type RspInvalid_data struct {
	Dummy uint8 // change as you need
}

// Login make session with nickname and enter stage
type ReqLogin_data struct {
	Dummy uint8 // change as you need
}
// Login make session with nickname and enter stage
type RspLogin_data struct {
	Dummy uint8 // change as you need
}

// Heartbeat prevent connection timeout
type ReqHeartbeat_data struct {
	Dummy uint8 // change as you need
}
// Heartbeat prevent connection timeout
type RspHeartbeat_data struct {
	Dummy uint8 // change as you need
}

// Chat chat to stage
type ReqChat_data struct {
	Dummy uint8 // change as you need
}
// Chat chat to stage
type RspChat_data struct {
	Dummy uint8 // change as you need
}

// Act send user action
type ReqAct_data struct {
	Dummy uint8 // change as you need
}
// Act send user action
type RspAct_data struct {
	Dummy uint8 // change as you need
}

// Invalid
type NotiInvalid_data struct {
	Dummy uint8 // change as you need
}

// StageInfo // game stage info to display
type NotiStageInfo_data struct {
	Dummy uint8 // change as you need
}

// StatsInfo // game stats info
type NotiStatsInfo_data struct {
	Dummy uint8 // change as you need
}

// StageChat
type NotiStageChat_data struct {
	Dummy uint8 // change as you need
}

*/
