// Code generated by "genenum -typename=TeamType -packagename=teamtype -basedir=enums -statstype=int"

package teamtype

import "fmt"

type TeamType uint8

const (
	Red    TeamType = iota // // red 255
	Blue                   // // blue 255
	Green                  // // green 255
	RRed                   // // red 0
	RBlue                  // // blue 0
	RGreen                 // // green 0

	TeamType_Count int = iota
)

var _TeamType2string = [TeamType_Count]string{
	Red:    "Red",
	Blue:   "Blue",
	Green:  "Green",
	RRed:   "RRed",
	RBlue:  "RBlue",
	RGreen: "RGreen",
}

func (e TeamType) String() string {
	if e >= 0 && e < TeamType(TeamType_Count) {
		return _TeamType2string[e]
	}
	return fmt.Sprintf("TeamType%d", uint8(e))
}

var _string2TeamType = map[string]TeamType{
	"Red":    Red,
	"Blue":   Blue,
	"Green":  Green,
	"RRed":   RRed,
	"RBlue":  RBlue,
	"RGreen": RGreen,
}

func String2TeamType(s string) (TeamType, bool) {
	v, b := _string2TeamType[s]
	return v, b
}
