// Code generated by "genprotocol -ver=0088cae732cbbc92d93b745e6f587bb9319940346f41b718b0293a0b56942cc3 -basedir=. -prefix=w2d -statstype=int"

package w2d_handlenoti

/* obj base demux fn map template

var DemuxNoti2ObjFnMap = [...]func(me interface{}, hd w2d_packet.Header, body interface{}) error {
w2d_idnoti.Invalid : objRecvNotiFn_Invalid, // Invalid
w2d_idnoti.StageInfo : objRecvNotiFn_StageInfo, // StageInfo // game stage info to display
w2d_idnoti.StatsInfo : objRecvNotiFn_StatsInfo, // StatsInfo // game stats info
w2d_idnoti.StageChat : objRecvNotiFn_StageChat, // StageChat

}

	// Invalid
	func objRecvNotiFn_Invalid(me interface{}, hd w2d_packet.Header, body interface{}) error {
		robj , ok := body.(*w2d_obj.NotiInvalid_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StageInfo // game stage info to display
	func objRecvNotiFn_StageInfo(me interface{}, hd w2d_packet.Header, body interface{}) error {
		robj , ok := body.(*w2d_obj.NotiStageInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StatsInfo // game stats info
	func objRecvNotiFn_StatsInfo(me interface{}, hd w2d_packet.Header, body interface{}) error {
		robj , ok := body.(*w2d_obj.NotiStatsInfo_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

	// StageChat
	func objRecvNotiFn_StageChat(me interface{}, hd w2d_packet.Header, body interface{}) error {
		robj , ok := body.(*w2d_obj.NotiStageChat_data)
		if !ok {
			return fmt.Errorf("packet mismatch %v", body )
		}
		return fmt.Errorf("Not implemented %v", robj)
	}

*/
